### ISSUE TITLE
Tip for excessive memory usage

### ISSUE THREAD

**Issue by pczerkas** [driftphp/server#100]
Driftphp app run by supervisord (restarts on exit),

this patch:
```
--- a/vendor/drift/server/src/Application.php
+++ b/vendor/drift/server/src/Application.php
@@ -49,6 +49,9 @@
  */
 class Application
 {
+    private const MAX_MEMORY_MB = 160;
+    private const GLOBAL_CONNECTION_COUNT = 'drift_connection_count';
+
     private LoopInterface $loop;
     private ServerContext $serverContext;
     private string $rootPath;
@@ -111,6 +114,26 @@
             $this->loop
         );

+        $GLOBALS[self::GLOBAL_CONNECTION_COUNT] = 0;
+
+        $socket->on('connection', function($conn) use ($kernelAdapter) {
+            $GLOBALS[self::GLOBAL_CONNECTION_COUNT]++;
+
+            $conn->on('close', function() use ($kernelAdapter) {
+                $GLOBALS[self::GLOBAL_CONNECTION_COUNT]--;
+
+                $memoryUsage = (int) (memory_get_usage() / 1000000);
+                if (
+                    0 === $GLOBALS[self::GLOBAL_CONNECTION_COUNT]
+                    && $memoryUsage > self::MAX_MEMORY_MB
+                ) {
+                    echo "Stopping due to excessive memory usage: $memoryUsage MB" . PHP_EOL;
+                    await($kernelAdapter->shutdown(), $this->loop);
+                    $this->loop->stop();
+                }
+            });
+        });
+
         $http = new HttpServer(
             $this->loop,
             new StreamingRequestMiddleware(),

```

plus socat relay on the front:

```
socat TCP4-LISTEN:"$WEB_PORT",reuseaddr,fork,bind="$POD_IP" TCP4:127.0.0.1:"$WEB_PORT",forever,interval=3
```
($POD_IP because I'm using Kubernetes)

This seamlesly restarts main service, while it is processing requests :)

**Comment by mmoreram** [comment]
Hello @pczerkas 

First of all, I'm VERY grateful for your sponsorship. Really. Big thanks for that. 

About the issue. To understand better.
You propose of nicely stop the server when there is too much memory in usage, so the server don't break current connections?
Memory usage should never be a problem here, and if you have memory problems (and I'm talking about my experience), a good way to solve this problem would be facing where is the memory problem.

What problem are you facing?
Maybe we can help with that.

**Comment by pczerkas** [comment]
Hello Marc,
I'd like to thank you for such a great project! For me it made possible to do exciting things :)

As to the issue, I'm using DriftPhp in a couple of places and in only some of them there are problem with growing memory usage. Mostly memory is released after some time.

But one of the projects is using Doctrine ORM, API Platform, Sentry, Easy Admin also with different Symfony bundles. It was rather hard for me to debug where memory is not released, so I choose this approach.

I think we can close this tip with adnotation that it is last-resort, temporary solution :)
WDYT?

**Comment by mmoreram** [comment]
@pczerkas thanks for your words. Really not used to listening them, and I appreciate them so much.

About the project.
Are you using DriftPHP with DoctrineORM at the same time? I mean. You're using the server with the Symfony server? You're using the Drift kernel? If you do such a thing, I would change some parts of the application, as the Drift kernel is not compatible with the Doctrine ORM, as this last one is blocking. You can only apply non-blocking parts in your application if the whole application is non-blocking. As soon as something (like the ORM of Doctrine) is blocking, then you have a non-production ready app.

**Comment by pczerkas** [comment]
@mmoreram I know that... But extensive multi-client tests shows that such "hybrid" solution is entirely possible, at least here what I have right now. 

I know, that clients will probaby suffer each-other requests times and overally it will not be as efficient, as fully non-blocking solution, though. I will put TODOs to look into it when time allows :)

**Comment by mmoreram** [comment]
Chack this small project to replace the ORM 

- https://github.com/driftphp/reactphp-dbal
- https://github.com/driftphp/dbal-bundle

About the changes you're asking, I don't feel comfortable to add an specific for-blocking feature in a project that aims to be (and force) non-blocking behavior. Instead of that, you can actually add a service that does exactly this in your project, outside the server, in your domain. That would work as well, and can work in your project during this hybrid mode.

**Comment by pczerkas** [comment]
Wasn't really assuming this will land in the code, was just a small tip ;)
Thanks, I'm closing it.
