### ISSUE TITLE
streamed request / response not handled correctly

### ISSUE THREAD

**Issue by Deltachaos** [driftphp/server#28]
In `src/RequestHandler.php#L195` streams are not handled correctly for the request body. Also in the response conversion, the streams get lost.

In `symfony/psr-http-message-bridge`, there is correct handling for streams.

**Comment by mmoreram** [comment]
Missing Streamed requests.

Implemented Streamed responses here - https://github.com/driftphp/server/commit/3ed8edb751f65a2c836a667c3ff82a8ca43f6e32

**Comment by mmoreram** [comment]
Opened a more specific Streamed requests Issue here - https://github.com/driftphp/server/issues/53

Please, if you have ideas about how to implement that, don't hesitate to comment there.

Thanks!
