### ISSUE TITLE
Set basic request server headers

### ISSUE THREAD

**Issue by Deltachaos** [driftphp/server#29]
There are no `$_SERVER` parameters available in the Symfony request. For the `isFromTrustedProxy` there is at least the `REMOTE_ADDR` header required.

**Comment by mmoreram** [comment]
@Deltachaos this might solve the problem - https://github.com/driftphp/server/pull/43/commits/9ff6490d9bf7569729b05e4c8b845eb907a55985#diff-79c0be2e5cf00e0d3654d992f3cf49b0R228
